# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/eoan64"
  #config.vm.network :forwarded_port, guest: 8443, host: 8443
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provision "shell", path: "provision.sh"

  config.vm.provider :virtualbox do |vb|
    vb.linked_clone = true
  end
end
